[Preferences]  
 
; Specifies the maximum number of units per player. Default is 200.  
; Warning: The higher the number, the more resources are required.  
; If the game slows down with higher numbers, you will need  
; more RAM and/or a faster CPU.  
 
UnitLimit = 5000;  
 
 
; Disable the use of DirectSound. Set this to 1 to disable  
; sound in the game. Set it to 0 to use sound normally.  
;  
; Disable the sound if you do not have a sound card or  
; the game crashes while trying to play sounds.  
 
NoDirectSound = 0;  
 
 
; Use the standard Windows multimedia interface for playing sounds  
; instead of DirectSound. Set this to 1 to use Windows sound, and  
; 0 to use DirectSound.  
;  
; Note: Setting this value to 1 will allow you to play the  
; game if DirectSound does not work properly on your system.  
; However, the audio quality will be greatly decreased,  
; especially during heavy battles. Also, you will not get any  
; audio narration with your mission briefings or any sound in the  
; movies.  
 
UseWindowsSound = 0;  
